#!/bin/bash
b=$(tput bold)
n=$(tput sgr0)
echo "\n${b} [[[|       Welcome to the BIFC Checker!      |]]]"
echo " [[[| Here is the list of available commands: |]]]${n}"
echo "\n01. ${b}make full${n}"
echo "       Compiles GNL source, header and libft with checker files."
echo "\n02. ${b}make eval${n}"
echo "       Starts the evaluation of the GNL project. get_next_line.c, get_next_line.h, author files are required among with libft/ folder. It is recommended to run ${b}make evalclean${n} first."
echo "\n03. ${b}make test_basic${n}"
echo "       Runs basic tests with 8 symbols per line and NewLine at the end. The tested input files are \"*_inp\". The correct answer files are \"*_cor\". The result file is named \"total\". All these files can be found at resources/tests/00.basic_tests/. Executable files are compiled with \"main.c\" for files and \"main2.c\" for stdio. They can be found at resources/mains/."
echo "\n04. ${b}make test_middle${n}"
echo "       Runs basic tests with 16 symbols per line and NewLine at the end. The tested input files are \"*_inp\". The correct answer files are \"*_cor\". The result file is named \"total\". All these files can be found at resources/tests/01.middle_tests/. Executable files are compiled with \"main.c\" for files and \"main2.c\" for stdio. They can be found at resources/mains/."
echo "\n05. ${b}make test_advanced${n}"
echo "       Runs advanced tests: tests with 4 symbols per line and NewLine at the end, tests woth 4, 8, 16 symbols per line and without NewLine at the endm test with one NewLine and an empty file. The tested input files are \"*_inp\". The correct answer files are \"*_cor\". The result file is named \"total\". All these files can be found at resources/tests/02.advanced_tests/. Executable files are compiled with \"main.c\" for files and \"main2.c\" for stdio. They can be found at resources/mains/."
echo "\n06. ${b}make test_error${n}"
echo "       Runs tests with incorrect file descriptors. The correct answer file is \"E_cor\". The result file is named \"total\". All these files can be found at resources/tests/03.error_tests/. Executable file is compiled with resources/mains/main3.c."
echo "\n07. ${b}make test_bonus${n}"
echo "       Runs bonus test. This test is opening three text files (resources/tests/04.bonus_tests/text[1..3]) and calls GNL function in random order. The result file is named \"total\" and can be found at the same folder. Executable file is compiled with resources/mains/main4.c."
echo "\n08. ${b}make test_all${n}"
echo "       Runs all of the tests test_basic, test_middle, test_advanced, test_error, test_bonus. The result can be seen by using ${b}make evalres${n}."
echo "\n09. ${b}make evalres${n}"
echo "       Shows the whole evaluation results with every single test info."
echo "\n10. ${b}make evalclean${n}"
echo "       Removes all files created during the evaluatuon (test results, logs, *.o files)."
echo "\n11. ${b}make aclean${n}"
echo "       Removes all *_ans files that are results of GNL testing."
echo "\n12. ${b}make norm${n}"
echo "       Checking Norminette for GNL files among with libft/ folder."
echo "\n13. ${b}make libre${n}"
echo "       Removes all libft *.o files among with libft.a and compiles them again. The results of these operations are saved in resources/logs/ lib_fclean and lib_make."
echo "\n14. ${b}make clean${n}"
echo "       Removes get_next_line.o."
echo "\n15. ${b}make fclean${n}"
echo "       Removes checker's executable files created while evaluation."
echo "\n16. ${b}make re${n}"
echo "       Recompiles GNL source, header and libft with checker files."
echo "\n17. ${b}make tar${n}"
echo "       Creates a .tar containing checker files previously running ${b}make evalclean${n}."
echo "\n18. ${b}make help${n}"
echo "       Shows available commands and describes their functionality.\n"